const url = [
  {
    id: "BRA",
    name: "Brazil",
    continents: "South America",
    capital: "Brasília",
    subregion: "South America",
    area: "8515767",
    population: "212559409",
    image: "https://flagcdn.com/br.svg",
  },

  {
    id: "ATA",
    name: "Antarctica",
    continents: "Antarctica",
    capital: "undefined",
    subregion: "undefined",
    area: "14000000",
    population: "1000",
    image: "https://flagcdn.com/aq.svg",
  },
  {
    id: "ALA",
    name: "Åland Islands",
    continents: "Europe",
    capital: "Mariehamn",
    subregion: "Northern Europe",
    area: "1580",
    population: "29458",
    image: "https://flagcdn.com/ax.svg",
  },
  {
    id: "SLB",
    name: "Solomon Islands",
    continents: "Oceania",
    capital: "Honiara",
    subregion: "Melanesia",
    area: "28896",
    population: "686878",
    image: "https://flagcdn.com/sb.svg",
  },
  {
    id: "ZAF",
    name: "South Africa",
    continents: "Africa",
    capital: "Pretoria, Bloemfontein, Cape Town",
    subregion: "Southern Africa",
    area: "1221037",
    population: "59308690",
    image: "https://flagcdn.com/za.svg",
  },
  {
    id: "AFG",
    name: "Afghanistan",
    continents: "Asia",
    capital: "Kabul",
    subregion: "Southern Asia",
    area: "652230",
    population: "40218234",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
  },
  {
    id: "GLP",
    name: "Guadeloupe",
    continents: "North America",
    capital: "Basse-Terre",
    subregion: "Caribbean",
    area: "1628",
    population: "400132",
    image: "https://flagcdn.com/gp.svg",
  },
  {
    id: "GNB",
    name: "Guinea-Bissau",
    continents: "Africa",
    capital: "Bissau",
    subregion: "Western Africa",
    area: "36125",
    population: "1967998",
    image: "https://flagcdn.com/gw.svg",
  },
  {
    id: "AGO",
    name: "Angola",
    continents: "Africa",
    capital: "Luanda",
    subregion: "Middle Africa",
    area: "1246700",
    population: "32866268",
    image: "https://flagcdn.com/ao.svg",
  },
  {
    id: "SVK",
    name: "Slovakia",
    continents: "Europe",
    capital: "Bratislava",
    subregion: "Central Europe",
    area: "49037",
    population: "5458827",
    image: "https://flagcdn.com/sk.svg",
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    continents: "Asia",
    capital: "Nur-Sultan",
    subregion: "Central Asia",
    area: "2724900",
    population: "18754440",
    image: "https://flagcdn.com/kz.svg",
  },
  {
    id: "SPM",
    name: "Saint Pierre and Miquelon",
    continents: "North America",
    capital: "Saint-Pierre",
    subregion: "North America",
    area: "242",
    population: "6069",
    image: "https://flagcdn.com/pm.svg",
  },
  {
    id: "THA",
    name: "Thailand",
    continents: "Asia",
    capital: "Bangkok",
    subregion: "South-Eastern Asia",
    area: "513120",
    population: "69799978",
    image: "https://flagcdn.com/th.svg",
  },
  {
    id: "OMN",
    name: "Oman",
    continents: "Asia",
    capital: "Muscat",
    subregion: "Western Asia",
    area: "309500",
    population: "5106622",
    image: "https://flagcdn.com/om.svg",
  },
  {
    id: "VNM",
    name: "Vietnam",
    continents: "Asia",
    capital: "Hanoi",
    subregion: "South-Eastern Asia",
    area: "331212",
    population: "97338583",
    image: "https://flagcdn.com/vn.svg",
  },
  {
    id: "ATG",
    name: "Antigua and Barbuda",
    continents: "North America",
    capital: "Saint John's",
    subregion: "Caribbean",
    area: "442",
    population: "97928",
    image: "https://flagcdn.com/ag.svg",
  },
  {
    id: "BWA",
    name: "Botswana",
    continents: "Africa",
    capital: "Gaborone",
    subregion: "Southern Africa",
    area: "582000",
    population: "2351625",
    image: "https://flagcdn.com/bw.svg",
  },
  {
    id: "NLD",
    name: "Netherlands",
    continents: "Europe",
    capital: "Amsterdam",
    subregion: "Western Europe",
    area: "41850",
    population: "16655799",
    image: "https://flagcdn.com/nl.svg",
  },
  {
    id: "NAM",
    name: "Namibia",
    continents: "Africa",
    capital: "Windhoek",
    subregion: "Southern Africa",
    area: "825615",
    population: "2540916",
    image: "https://flagcdn.com/na.svg",
  },
  {
    id: "UGA",
    name: "Uganda",
    continents: "Africa",
    capital: "Kampala",
    subregion: "Eastern Africa",
    area: "241550",
    population: "45741000",
    image: "https://flagcdn.com/ug.svg",
  },
  {
    id: "ABW",
    name: "Aruba",
    continents: "North America",
    capital: "Oranjestad",
    subregion: "Caribbean",
    area: "180",
    population: "106766",
    image: "https://flagcdn.com/aw.svg",
  },
  {
    id: "LIE",
    name: "Liechtenstein",
    continents: "Europe",
    capital: "Vaduz",
    subregion: "Western Europe",
    area: "160",
    population: "38137",
    image: "https://flagcdn.com/li.svg",
  },
  {
    id: "PER",
    name: "Peru",
    continents: "South America",
    capital: "Lima",
    subregion: "South America",
    area: "1285216",
    population: "32971846",
    image: "https://flagcdn.com/pe.svg",
  },
  {
    id: "CAF",
    name: "Central African Republic",
    continents: "Africa",
    capital: "Bangui",
    subregion: "Middle Africa",
    area: "622984",
    population: "4829764",
    image: "https://flagcdn.com/cf.svg",
  },
  {
    id: "MNE",
    name: "Montenegro",
    continents: "Europe",
    capital: "Podgorica",
    subregion: "Southeast Europe",
    area: "13812",
    population: "621718",
    image: "https://flagcdn.com/me.svg",
  },
  {
    id: "COG",
    name: "Republic of the Congo",
    continents: "Africa",
    capital: "Brazzaville",
    subregion: "Middle Africa",
    area: "342000",
    population: "89561404",
    image: "https://flagcdn.com/cg.svg",
  },
  {
    id: "BLZ",
    name: "Belize",
    continents: "North America",
    capital: "Belmopan",
    subregion: "Central America",
    area: "22966",
    population: "397621",
    image: "https://flagcdn.com/bz.svg",
  },
  {
    id: "BOL",
    name: "Bolivia",
    continents: "South America",
    capital: "Sucre",
    subregion: "South America",
    area: "1098581",
    population: "11673029",
    image: "https://flagcdn.com/bo.svg",
  },
  {
    id: "BFA",
    name: "Burkina Faso",
    continents: "Africa",
    capital: "Ouagadougou",
    subregion: "Western Africa",
    area: "272967",
    population: "20903278",
    image: "https://flagcdn.com/bf.svg",
  },
  {
    id: "MAC",
    name: "Macau",
    continents: "Asia",
    capital: "undefined",
    subregion: "Eastern Asia",
    area: "30",
    population: "649342",
    image: "https://flagcdn.com/mo.svg",
  },
  {
    id: "TKL",
    name: "Tokelau",
    continents: "Oceania",
    capital: "Fakaofo",
    subregion: "Polynesia",
    area: "12",
    population: "1411",
    image: "https://flagcdn.com/tk.svg",
  },
  {
    id: "FIN",
    name: "Finland",
    continents: "Europe",
    capital: "Helsinki",
    subregion: "Northern Europe",
    area: "338424",
    population: "5530719",
    image: "https://flagcdn.com/fi.svg",
  },
  {
    id: "MAR",
    name: "Morocco",
    continents: "Africa",
    capital: "Rabat",
    subregion: "Northern Africa",
    area: "446550",
    population: "36910558",
    image: "https://flagcdn.com/ma.svg",
  },
  {
    id: "SVN",
    name: "Slovenia",
    continents: "Europe",
    capital: "Ljubljana",
    subregion: "Central Europe",
    area: "20273",
    population: "2100126",
    image: "https://flagcdn.com/si.svg",
  },
  {
    id: "HMD",
    name: "Heard Island and McDonald Islands",
    continents: "Antarctica",
    capital: "undefined",
    subregion: "undefined",
    area: "412",
    population: "0",
    image: "https://flagcdn.com/hm.svg",
  },
  {
    id: "BDI",
    name: "Burundi",
    continents: "Africa",
    capital: "Gitega",
    subregion: "Eastern Africa",
    area: "27834",
    population: "11890781",
    image: "https://flagcdn.com/bi.svg",
  },
  {
    id: "NIU",
    name: "Niue",
    continents: "Oceania",
    capital: "Alofi",
    subregion: "Polynesia",
    area: "260",
    population: "1470",
    image: "https://flagcdn.com/nu.svg",
  },
  {
    id: "SUR",
    name: "Suriname",
    continents: "South America",
    capital: "Paramaribo",
    subregion: "South America",
    area: "163820",
    population: "586634",
    image: "https://flagcdn.com/sr.svg",
  },
  {
    id: "CCK",
    name: "Cocos (Keeling) Islands",
    continents: "Asia",
    capital: "West Island",
    subregion: "Australia and New Zealand",
    area: "14",
    population: "544",
    image: "https://flagcdn.com/cc.svg",
  },
  {
    id: "MRT",
    name: "Mauritania",
    continents: "Africa",
    capital: "Nouakchott",
    subregion: "Western Africa",
    area: "1030700",
    population: "4649660",
    image: "https://flagcdn.com/mr.svg",
  },
  {
    id: "DJI",
    name: "Djibouti",
    continents: "Africa",
    capital: "Djibouti",
    subregion: "Eastern Africa",
    area: "23200",
    population: "988002",
    image: "https://flagcdn.com/dj.svg",
  },
  {
    id: "VEN",
    name: "Venezuela",
    continents: "South America",
    capital: "Caracas",
    subregion: "South America",
    area: "916445",
    population: "28435943",
    image: "https://flagcdn.com/ve.svg",
  },
  {
    id: "AIA",
    name: "Anguilla",
    continents: "North America",
    capital: "The Valley",
    subregion: "Caribbean",
    area: "91",
    population: "13452",
    image: "https://flagcdn.com/ai.svg",
  },
  {
    id: "HTI",
    name: "Haiti",
    continents: "North America",
    capital: "Port-au-Prince",
    subregion: "Caribbean",
    area: "27750",
    population: "11402533",
    image: "https://flagcdn.com/ht.svg",
  },
  {
    id: "JOR",
    name: "Jordan",
    continents: "Asia",
    capital: "Amman",
    subregion: "Western Asia",
    area: "89342",
    population: "10203140",
    image: "https://flagcdn.com/jo.svg",
  },
  {
    id: "SLE",
    name: "Sierra Leone",
    continents: "Africa",
    capital: "Freetown",
    subregion: "Western Africa",
    area: "71740",
    population: "7976985",
    image: "https://flagcdn.com/sl.svg",
  },
  {
    id: "MNP",
    name: "Northern Mariana Islands",
    continents: "Oceania",
    capital: "Saipan",
    subregion: "Micronesia",
    area: "464",
    population: "57557",
    image: "https://flagcdn.com/mp.svg",
  },
  {
    id: "TKM",
    name: "Turkmenistan",
    continents: "Asia",
    capital: "Ashgabat",
    subregion: "Central Asia",
    area: "488100",
    population: "6031187",
    image: "https://flagcdn.com/tm.svg",
  },
  {
    id: "CIV",
    name: "Ivory Coast",
    continents: "Africa",
    capital: "Yamoussoukro",
    subregion: "Western Africa",
    area: "322463",
    population: "26378275",
    image: "https://flagcdn.com/ci.svg",
  },
  {
    id: "KIR",
    name: "Kiribati",
    continents: "Oceania",
    capital: "South Tarawa",
    subregion: "Micronesia",
    area: "811",
    population: "119446",
    image: "https://flagcdn.com/ki.svg",
  },
  {
    id: "SGP",
    name: "Singapore",
    continents: "Asia",
    capital: "Singapore",
    subregion: "South-Eastern Asia",
    area: "710",
    population: "5685807",
    image: "https://flagcdn.com/sg.svg",
  },
  {
    id: "EST",
    name: "Estonia",
    continents: "Europe",
    capital: "Tallinn",
    subregion: "Northern Europe",
    area: "45227",
    population: "1331057",
    image: "https://flagcdn.com/ee.svg",
  },
  {
    id: "URY",
    name: "Uruguay",
    continents: "South America",
    capital: "Montevideo",
    subregion: "South America",
    area: "181034",
    population: "3473727",
    image: "https://flagcdn.com/uy.svg",
  },
  {
    id: "PRT",
    name: "Portugal",
    continents: "Europe",
    capital: "Lisbon",
    subregion: "Southern Europe",
    area: "92090",
    population: "10305564",
    image: "https://flagcdn.com/pt.svg",
  },
  {
    id: "GUY",
    name: "Guyana",
    continents: "South America",
    capital: "Georgetown",
    subregion: "South America",
    area: "214969",
    population: "786559",
    image: "https://flagcdn.com/gy.svg",
  },
  {
    id: "LBY",
    name: "Libya",
    continents: "Africa",
    capital: "Tripoli",
    subregion: "Northern Africa",
    area: "1759540",
    population: "6871287",
    image: "https://flagcdn.com/ly.svg",
  },
  {
    id: "MLT",
    name: "Malta",
    continents: "Europe",
    capital: "Valletta",
    subregion: "Southern Europe",
    area: "316",
    population: "525285",
    image: "https://flagcdn.com/mt.svg",
  },
  {
    id: "USA",
    name: "United States",
    continents: "North America",
    capital: "Washington, D.C.",
    subregion: "North America",
    area: "9372610",
    population: "329484123",
    image: "https://flagcdn.com/us.svg",
  },
  {
    id: "ARE",
    name: "United Arab Emirates",
    continents: "Asia",
    capital: "Abu Dhabi",
    subregion: "Western Asia",
    area: "83600",
    population: "9890400",
    image: "https://flagcdn.com/ae.svg",
  },
  {
    id: "TZA",
    name: "Tanzania",
    continents: "Africa",
    capital: "Dodoma",
    subregion: "Eastern Africa",
    area: "945087",
    population: "59734213",
    image: "https://flagcdn.com/tz.svg",
  },
  {
    id: "IRL",
    name: "Ireland",
    continents: "Europe",
    capital: "Dublin",
    subregion: "Northern Europe",
    area: "70273",
    population: "4994724",
    image: "https://flagcdn.com/ie.svg",
  },
  {
    id: "IOT",
    name: "British Indian Ocean Territory",
    continents: "Asia",
    capital: "Diego Garcia",
    subregion: "Eastern Africa",
    area: "60",
    population: "3000",
    image: "https://flagcdn.com/io.svg",
  },
  {
    id: "LTU",
    name: "Lithuania",
    continents: "Europe",
    capital: "Vilnius",
    subregion: "Northern Europe",
    area: "65300",
    population: "2794700",
    image: "https://flagcdn.com/lt.svg",
  },
  {
    id: "PLW",
    name: "Palau",
    continents: "Oceania",
    capital: "Ngerulmud",
    subregion: "Micronesia",
    area: "459",
    population: "18092",
    image: "https://flagcdn.com/pw.svg",
  },
  {
    id: "PCN",
    name: "Pitcairn Islands",
    continents: "Oceania",
    capital: "Adamstown",
    subregion: "Polynesia",
    area: "47",
    population: "56",
    image: "https://flagcdn.com/pn.svg",
  },
  {
    id: "GEO",
    name: "Georgia",
    continents: "Asia",
    capital: "Tbilisi",
    subregion: "Western Asia",
    area: "69700",
    population: "3714000",
    image: "https://flagcdn.com/ge.svg",
  },
  {
    id: "MYS",
    name: "Malaysia",
    continents: "Asia",
    capital: "Kuala Lumpur",
    subregion: "South-Eastern Asia",
    area: "330803",
    population: "32365998",
    image: "https://flagcdn.com/my.svg",
  },
  {
    id: "MSR",
    name: "Montserrat",
    continents: "North America",
    capital: "Plymouth",
    subregion: "Caribbean",
    area: "102",
    population: "4922",
    image: "https://flagcdn.com/ms.svg",
  },
  {
    id: "PRY",
    name: "Paraguay",
    continents: "South America",
    capital: "Asunción",
    subregion: "South America",
    area: "406752",
    population: "7132530",
    image: "https://flagcdn.com/py.svg",
  },
  {
    id: "QAT",
    name: "Qatar",
    continents: "Asia",
    capital: "Doha",
    subregion: "Western Asia",
    area: "11586",
    population: "2881060",
    image: "https://flagcdn.com/qa.svg",
  },
  {
    id: "KNA",
    name: "Saint Kitts and Nevis",
    continents: "North America",
    capital: "Basseterre",
    subregion: "Caribbean",
    area: "261",
    population: "53192",
    image: "https://flagcdn.com/kn.svg",
  },
  {
    id: "HKG",
    name: "Hong Kong",
    continents: "Asia",
    capital: "City of Victoria",
    subregion: "Eastern Asia",
    area: "1104",
    population: "7500700",
    image: "https://flagcdn.com/hk.svg",
  },
  {
    id: "PSE",
    name: "Palestine",
    continents: "Asia",
    capital: "Ramallah",
    subregion: "Western Asia",
    area: "6220",
    population: "4803269",
    image: "https://flagcdn.com/ps.svg",
  },
  {
    id: "TCA",
    name: "Turks and Caicos Islands",
    continents: "North America",
    capital: "Cockburn Town",
    subregion: "Caribbean",
    area: "948",
    population: "38718",
    image: "https://flagcdn.com/tc.svg",
  },
  {
    id: "ALB",
    name: "Albania",
    continents: "Europe",
    capital: "Tirana",
    subregion: "Southeast Europe",
    area: "28748",
    population: "2837743",
    image: "https://flagcdn.com/al.svg",
  },
  {
    id: "WLF",
    name: "Wallis and Futuna",
    continents: "Oceania",
    capital: "Mata-Utu",
    subregion: "Polynesia",
    area: "142",
    population: "11750",
    image: "https://flagcdn.com/wf.svg",
  },
  {
    id: "PAN",
    name: "Panama",
    continents: "North America",
    capital: "Panama City",
    subregion: "Central America",
    area: "75417",
    population: "4314768",
    image: "https://flagcdn.com/pa.svg",
  },
  {
    id: "SMR",
    name: "San Marino",
    continents: "Europe",
    capital: "City of San Marino",
    subregion: "Southern Europe",
    area: "61",
    population: "33938",
    image: "https://flagcdn.com/sm.svg",
  },
  {
    id: "ECU",
    name: "Ecuador",
    continents: "South America",
    capital: "Quito",
    subregion: "South America",
    area: "276841",
    population: "17643060",
    image: "https://flagcdn.com/ec.svg",
  },
  {
    id: "IND",
    name: "India",
    continents: "Asia",
    capital: "New Delhi",
    subregion: "Southern Asia",
    area: "3287590",
    population: "1380004385",
    image: "https://flagcdn.com/in.svg",
  },
  {
    id: "JAM",
    name: "Jamaica",
    continents: "North America",
    capital: "Kingston",
    subregion: "Caribbean",
    area: "10991",
    population: "2961161",
    image: "https://flagcdn.com/jm.svg",
  },
  {
    id: "NCL",
    name: "New Caledonia",
    continents: "Oceania",
    capital: "Nouméa",
    subregion: "Melanesia",
    area: "18575",
    population: "271960",
    image: "https://flagcdn.com/nc.svg",
  },
  {
    id: "MYT",
    name: "Mayotte",
    continents: "Africa",
    capital: "Mamoudzou",
    subregion: "Eastern Africa",
    area: "374",
    population: "226915",
    image: "https://flagcdn.com/yt.svg",
  },
  {
    id: "AZE",
    name: "Azerbaijan",
    continents: "Asia",
    capital: "Baku",
    subregion: "Western Asia",
    area: "86600",
    population: "10110116",
    image: "https://flagcdn.com/az.svg",
  },
  {
    id: "ETH",
    name: "Ethiopia",
    continents: "Africa",
    capital: "Addis Ababa",
    subregion: "Eastern Africa",
    area: "1104300",
    population: "114963583",
    image: "https://flagcdn.com/et.svg",
  },
  {
    id: "AND",
    name: "Andorra",
    continents: "Europe",
    capital: "Andorra la Vella",
    subregion: "Southern Europe",
    area: "468",
    population: "77265",
    image: "https://flagcdn.com/ad.svg",
  },
  {
    id: "LUX",
    name: "Luxembourg",
    continents: "Europe",
    capital: "Luxembourg",
    subregion: "Western Europe",
    area: "2586",
    population: "632275",
    image: "https://flagcdn.com/lu.svg",
  },
  {
    id: "KHM",
    name: "Cambodia",
    continents: "Asia",
    capital: "Phnom Penh",
    subregion: "South-Eastern Asia",
    area: "181035",
    population: "16718971",
    image: "https://flagcdn.com/kh.svg",
  },
  {
    id: "MDV",
    name: "Maldives",
    continents: "Asia",
    capital: "Malé",
    subregion: "Southern Asia",
    area: "300",
    population: "540542",
    image: "https://flagcdn.com/mv.svg",
  },
  {
    id: "SJM",
    name: "Svalbard and Jan Mayen",
    continents: "Europe",
    capital: "Longyearbyen",
    subregion: "Northern Europe",
    area: "-1",
    population: "2562",
    image: "https://flagcdn.com/sj.svg",
  },
  {
    id: "VIR",
    name: "United States Virgin Islands",
    continents: "North America",
    capital: "Charlotte Amalie",
    subregion: "Caribbean",
    area: "347",
    population: "106290",
    image: "https://flagcdn.com/vi.svg",
  },
  {
    id: "GUM",
    name: "Guam",
    continents: "Oceania",
    capital: "Hagåtña",
    subregion: "Micronesia",
    area: "549",
    population: "168783",
    image: "https://flagcdn.com/gu.svg",
  },
  {
    id: "LKA",
    name: "Sri Lanka",
    continents: "Asia",
    capital: "Sri Jayawardenepura Kotte",
    subregion: "Southern Asia",
    area: "65610",
    population: "21919000",
    image: "https://flagcdn.com/lk.svg",
  },
  {
    id: "CYP",
    name: "Cyprus",
    continents: "Europe",
    capital: "Nicosia",
    subregion: "Southern Europe",
    area: "9251",
    population: "1207361",
    image: "https://flagcdn.com/cy.svg",
  },
  {
    id: "MKD",
    name: "North Macedonia",
    continents: "Europe",
    capital: "Skopje",
    subregion: "Southeast Europe",
    area: "25713",
    population: "2077132",
    image: "https://flagcdn.com/mk.svg",
  },
  {
    id: "CPV",
    name: "Cape Verde",
    continents: "Africa",
    capital: "Praia",
    subregion: "Western Africa",
    area: "4033",
    population: "555988",
    image: "https://flagcdn.com/cv.svg",
  },
  {
    id: "BLR",
    name: "Belarus",
    continents: "Europe",
    capital: "Minsk",
    subregion: "Eastern Europe",
    area: "207600",
    population: "9398861",
    image: "https://flagcdn.com/by.svg",
  },
  {
    id: "NFK",
    name: "Norfolk Island",
    continents: "Oceania",
    capital: "Kingston",
    subregion: "Australia and New Zealand",
    area: "36",
    population: "2302",
    image: "https://flagcdn.com/nf.svg",
  },
  {
    id: "NIC",
    name: "Nicaragua",
    continents: "North America",
    capital: "Managua",
    subregion: "Central America",
    area: "130373",
    population: "6624554",
    image: "https://flagcdn.com/ni.svg",
  },
  {
    id: "SAU",
    name: "Saudi Arabia",
    continents: "Asia",
    capital: "Riyadh",
    subregion: "Western Asia",
    area: "2149690",
    population: "34813867",
    image: "https://flagcdn.com/sa.svg",
  },
  {
    id: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    continents: "Africa",
    capital: "Jamestown",
    subregion: "Western Africa",
    area: "394",
    population: "53192",
    image: "https://flagcdn.com/sh.svg",
  },
  {
    id: "TTO",
    name: "Trinidad and Tobago",
    continents: "North America",
    capital: "Port of Spain",
    subregion: "Caribbean",
    area: "5130",
    population: "1399491",
    image: "https://flagcdn.com/tt.svg",
  },
  {
    id: "AUS",
    name: "Australia",
    continents: "Oceania",
    capital: "Canberra",
    subregion: "Australia and New Zealand",
    area: "7692024",
    population: "25687041",
    image: "https://flagcdn.com/au.svg",
  },
  {
    id: "CXR",
    name: "Christmas Island",
    continents: "Asia",
    capital: "Flying Fish Cove",
    subregion: "Australia and New Zealand",
    area: "135",
    population: "2072",
    image: "https://flagcdn.com/cx.svg",
  },
  {
    id: "FLK",
    name: "Falkland Islands",
    continents: "South America",
    capital: "Stanley",
    subregion: "South America",
    area: "12173",
    population: "2563",
    image: "https://flagcdn.com/fk.svg",
  },
  {
    id: "MWI",
    name: "Malawi",
    continents: "Africa",
    capital: "Lilongwe",
    subregion: "Eastern Africa",
    area: "118484",
    population: "19129955",
    image: "https://flagcdn.com/mw.svg",
  },
  {
    id: "VGB",
    name: "British Virgin Islands",
    continents: "North America",
    capital: "Road Town",
    subregion: "Caribbean",
    area: "151",
    population: "30237",
    image: "https://flagcdn.com/vg.svg",
  },
  {
    id: "BVT",
    name: "Bouvet Island",
    continents: "Antarctica",
    capital: "undefined",
    subregion: "undefined",
    area: "49",
    population: "0",
    image: "https://flagcdn.com/bv.svg",
  },
  {
    id: "KGZ",
    name: "Kyrgyzstan",
    continents: "Asia",
    capital: "Bishkek",
    subregion: "Central Asia",
    area: "199951",
    population: "6591600",
    image: "https://flagcdn.com/kg.svg",
  },
  {
    id: "BLM",
    name: "Saint Barthélemy",
    continents: "North America",
    capital: "Gustavia",
    subregion: "Caribbean",
    area: "21",
    population: "4255",
    image: "https://flagcdn.com/bl.svg",
  },
  {
    id: "ERI",
    name: "Eritrea",
    continents: "Africa",
    capital: "Asmara",
    subregion: "Eastern Africa",
    area: "117600",
    population: "5352000",
    image: "https://flagcdn.com/er.svg",
  },
  {
    id: "ISR",
    name: "Israel",
    continents: "Asia",
    capital: "Jerusalem",
    subregion: "Western Asia",
    area: "20770",
    population: "9216900",
    image: "https://flagcdn.com/il.svg",
  },
  {
    id: "MDA",
    name: "Moldova",
    continents: "Europe",
    capital: "Chișinău",
    subregion: "Eastern Europe",
    area: "33846",
    population: "2617820",
    image: "https://flagcdn.com/md.svg",
  },
  {
    id: "PYF",
    name: "French Polynesia",
    continents: "Oceania",
    capital: "Papeetē",
    subregion: "Polynesia",
    area: "4167",
    population: "280904",
    image: "https://flagcdn.com/pf.svg",
  },
  {
    id: "GRD",
    name: "Grenada",
    continents: "North America",
    capital: "St. George's",
    subregion: "Caribbean",
    area: "344",
    population: "112519",
    image: "https://flagcdn.com/gd.svg",
  },
  {
    id: "VUT",
    name: "Vanuatu",
    continents: "Oceania",
    capital: "Port Vila",
    subregion: "Melanesia",
    area: "12189",
    population: "307150",
    image: "https://flagcdn.com/vu.svg",
  },
  {
    id: "FRO",
    name: "Faroe Islands",
    continents: "Europe",
    capital: "Tórshavn",
    subregion: "Northern Europe",
    area: "1393",
    population: "48865",
    image: "https://flagcdn.com/fo.svg",
  },
  {
    id: "PRK",
    name: "North Korea",
    continents: "Asia",
    capital: "Pyongyang",
    subregion: "Eastern Asia",
    area: "120538",
    population: "25778815",
    image: "https://flagcdn.com/kp.svg",
  },
  {
    id: "CHN",
    name: "China",
    continents: "Asia",
    capital: "Beijing",
    subregion: "Eastern Asia",
    area: "9706961",
    population: "1402112000",
    image: "https://flagcdn.com/cn.svg",
  },
  {
    id: "MCO",
    name: "Monaco",
    continents: "Europe",
    capital: "Monaco",
    subregion: "Western Europe",
    area: "2.02",
    population: "39244",
    image: "https://flagcdn.com/mc.svg",
  },
  {
    id: "SLV",
    name: "El Salvador",
    continents: "North America",
    capital: "San Salvador",
    subregion: "Central America",
    area: "21041",
    population: "6486201",
    image: "https://flagcdn.com/sv.svg",
  },
  {
    id: "TUR",
    name: "Turkey",
    continents: "Asia",
    capital: "Ankara",
    subregion: "Western Asia",
    area: "783562",
    population: "84339067",
    image: "https://flagcdn.com/tr.svg",
  },
  {
    id: "UZB",
    name: "Uzbekistan",
    continents: "Asia",
    capital: "Tashkent",
    subregion: "Central Asia",
    area: "447400",
    population: "34232050",
    image: "https://flagcdn.com/uz.svg",
  },
  {
    id: "LBR",
    name: "Liberia",
    continents: "Africa",
    capital: "Monrovia",
    subregion: "Western Africa",
    area: "111369",
    population: "5057677",
    image: "https://flagcdn.com/lr.svg",
  },
  {
    id: "LAO",
    name: "Laos",
    continents: "Asia",
    capital: "Vientiane",
    subregion: "South-Eastern Asia",
    area: "236800",
    population: "7275556",
    image: "https://flagcdn.com/la.svg",
  },
  {
    id: "ISL",
    name: "Iceland",
    continents: "Europe",
    capital: "Reykjavik",
    subregion: "Northern Europe",
    area: "103000",
    population: "366425",
    image: "https://flagcdn.com/is.svg",
  },
  {
    id: "COK",
    name: "Cook Islands",
    continents: "Oceania",
    capital: "Avarua",
    subregion: "Polynesia",
    area: "236",
    population: "18100",
    image: "https://flagcdn.com/ck.svg",
  },
  {
    id: "STP",
    name: "São Tomé and Príncipe",
    continents: "Africa",
    capital: "São Tomé",
    subregion: "Middle Africa",
    area: "964",
    population: "219161",
    image: "https://flagcdn.com/st.svg",
  },
  {
    id: "MEX",
    name: "Mexico",
    continents: "North America",
    capital: "Mexico City",
    subregion: "North America",
    area: "1964375",
    population: "128932753",
    image: "https://flagcdn.com/mx.svg",
  },
  {
    id: "JEY",
    name: "Jersey",
    continents: "Europe",
    capital: "Saint Helier",
    subregion: "Northern Europe",
    area: "116",
    population: "100800",
    image: "https://flagcdn.com/je.svg",
  },
  {
    id: "MDG",
    name: "Madagascar",
    continents: "Africa",
    capital: "Antananarivo",
    subregion: "Eastern Africa",
    area: "587041",
    population: "27691019",
    image: "https://flagcdn.com/mg.svg",
  },
  {
    id: "CHE",
    name: "Switzerland",
    continents: "Europe",
    capital: "Bern",
    subregion: "Western Europe",
    area: "41284",
    population: "8654622",
    image: "https://flagcdn.com/ch.svg",
  },
  {
    id: "GGY",
    name: "Guernsey",
    continents: "Europe",
    capital: "St. Peter Port",
    subregion: "Northern Europe",
    area: "78",
    population: "62999",
    image: "https://flagcdn.com/gg.svg",
  },
  {
    id: "SWZ",
    name: "Eswatini",
    continents: "Africa",
    capital: "Mbabane",
    subregion: "Southern Africa",
    area: "17364",
    population: "1160164",
    image: "https://flagcdn.com/sz.svg",
  },
  {
    id: "RWA",
    name: "Rwanda",
    continents: "Africa",
    capital: "Kigali",
    subregion: "Eastern Africa",
    area: "26338",
    population: "12952209",
    image: "https://flagcdn.com/rw.svg",
  },
  {
    id: "CRI",
    name: "Costa Rica",
    continents: "North America",
    capital: "San José",
    subregion: "Central America",
    area: "51100",
    population: "5094114",
    image: "https://flagcdn.com/cr.svg",
  },
  {
    id: "GAB",
    name: "Gabon",
    continents: "Africa",
    capital: "Libreville",
    subregion: "Middle Africa",
    area: "267668",
    population: "2225728",
    image: "https://flagcdn.com/ga.svg",
  },
  {
    id: "BEL",
    name: "Belgium",
    continents: "Europe",
    capital: "Brussels",
    subregion: "Western Europe",
    area: "30528",
    population: "11555997",
    image: "https://flagcdn.com/be.svg",
  },
  {
    id: "SDN",
    name: "Sudan",
    continents: "Africa",
    capital: "Khartoum",
    subregion: "Northern Africa",
    area: "1886068",
    population: "43849269",
    image: "https://flagcdn.com/sd.svg",
  },
  {
    id: "LCA",
    name: "Saint Lucia",
    continents: "North America",
    capital: "Castries",
    subregion: "Caribbean",
    area: "616",
    population: "183629",
    image: "https://flagcdn.com/lc.svg",
  },
  {
    id: "LBN",
    name: "Lebanon",
    continents: "Asia",
    capital: "Beirut",
    subregion: "Western Asia",
    area: "10452",
    population: "6825442",
    image: "https://flagcdn.com/lb.svg",
  },
  {
    id: "COD",
    name: "DR Congo",
    continents: "Africa",
    capital: "Kinshasa",
    subregion: "Middle Africa",
    area: "2344858",
    population: "89561404",
    image: "https://flagcdn.com/cd.svg",
  },
  {
    id: "CUB",
    name: "Cuba",
    continents: "North America",
    capital: "Havana",
    subregion: "Caribbean",
    area: "109884",
    population: "11326616",
    image: "https://flagcdn.com/cu.svg",
  },
  {
    id: "ZMB",
    name: "Zambia",
    continents: "Africa",
    capital: "Lusaka",
    subregion: "Eastern Africa",
    area: "752612",
    population: "18383956",
    image: "https://flagcdn.com/zm.svg",
  },
  {
    id: "BIH",
    name: "Bosnia and Herzegovina",
    continents: "Europe",
    capital: "Sarajevo",
    subregion: "Southeast Europe",
    area: "51209",
    population: "3280815",
    image: "https://flagcdn.com/ba.svg",
  },
  {
    id: "KEN",
    name: "Kenya",
    continents: "Africa",
    capital: "Nairobi",
    subregion: "Eastern Africa",
    area: "580367",
    population: "53771300",
    image: "https://flagcdn.com/ke.svg",
  },
  {
    id: "MOZ",
    name: "Mozambique",
    continents: "Africa",
    capital: "Maputo",
    subregion: "Eastern Africa",
    area: "801590",
    population: "31255435",
    image: "https://flagcdn.com/mz.svg",
  },
  {
    id: "ARM",
    name: "Armenia",
    continents: "Asia",
    capital: "Yerevan",
    subregion: "Western Asia",
    area: "29743",
    population: "2963234",
    image: "https://flagcdn.com/am.svg",
  },
  {
    id: "CHL",
    name: "Chile",
    continents: "South America",
    capital: "Santiago",
    subregion: "South America",
    area: "756102",
    population: "19116209",
    image: "https://flagcdn.com/cl.svg",
  },
  {
    id: "DMA",
    name: "Dominica",
    continents: "North America",
    capital: "Roseau",
    subregion: "Caribbean",
    area: "751",
    population: "71991",
    image: "https://flagcdn.com/dm.svg",
  },
  {
    id: "MNG",
    name: "Mongolia",
    continents: "Asia",
    capital: "Ulan Bator",
    subregion: "Eastern Asia",
    area: "1564110",
    population: "3278292",
    image: "https://flagcdn.com/mn.svg",
  },
  {
    id: "NPL",
    name: "Nepal",
    continents: "Asia",
    capital: "Kathmandu",
    subregion: "Southern Asia",
    area: "147181",
    population: "29136808",
    image: "https://flagcdn.com/np.svg",
  },
  {
    id: "CZE",
    name: "Czechia",
    continents: "Europe",
    capital: "Prague",
    subregion: "Central Europe",
    area: "78865",
    population: "10698896",
    image: "https://flagcdn.com/cz.svg",
  },
  {
    id: "ESH",
    name: "Western Sahara",
    continents: "Africa",
    capital: "El Aaiún",
    subregion: "Northern Africa",
    area: "266000",
    population: "510713",
    image: "https://flagcdn.com/eh.svg",
  },
  {
    id: "GMB",
    name: "Gambia",
    continents: "Africa",
    capital: "Banjul",
    subregion: "Western Africa",
    area: "10689",
    population: "2416664",
    image: "https://flagcdn.com/gm.svg",
  },
  {
    id: "GHA",
    name: "Ghana",
    continents: "Africa",
    capital: "Accra",
    subregion: "Western Africa",
    area: "238533",
    population: "31072945",
    image: "https://flagcdn.com/gh.svg",
  },
  {
    id: "IRQ",
    name: "Iraq",
    continents: "Asia",
    capital: "Baghdad",
    subregion: "Western Asia",
    area: "438317",
    population: "40222503",
    image: "https://flagcdn.com/iq.svg",
  },
  {
    id: "FSM",
    name: "Micronesia",
    continents: "Oceania",
    capital: "Palikir",
    subregion: "Micronesia",
    area: "702",
    population: "115021",
    image: "https://flagcdn.com/fm.svg",
  },
  {
    id: "MTQ",
    name: "Martinique",
    continents: "North America",
    capital: "Fort-de-France",
    subregion: "Caribbean",
    area: "1128",
    population: "378243",
    image: "https://flagcdn.com/mq.svg",
  },
  {
    id: "FRA",
    name: "France",
    continents: "Europe",
    capital: "Paris",
    subregion: "Western Europe",
    area: "551695",
    population: "67391582",
    image: "https://flagcdn.com/fr.svg",
  },
  {
    id: "LSO",
    name: "Lesotho",
    continents: "Africa",
    capital: "Maseru",
    subregion: "Southern Africa",
    area: "30355",
    population: "2142252",
    image: "https://flagcdn.com/ls.svg",
  },
  {
    id: "NRU",
    name: "Nauru",
    continents: "Oceania",
    capital: "Yaren",
    subregion: "Micronesia",
    area: "21",
    population: "10834",
    image: "https://flagcdn.com/nr.svg",
  },
  {
    id: "UKR",
    name: "Ukraine",
    continents: "Europe",
    capital: "Kyiv",
    subregion: "Eastern Europe",
    area: "603500",
    population: "44134693",
    image: "https://flagcdn.com/ua.svg",
  },
  {
    id: "NZL",
    name: "New Zealand",
    continents: "Oceania",
    capital: "Wellington",
    subregion: "Australia and New Zealand",
    area: "270467",
    population: "5084300",
    image: "https://flagcdn.com/nz.svg",
  },
  {
    id: "IMN",
    name: "Isle of Man",
    continents: "Europe",
    capital: "Douglas",
    subregion: "Northern Europe",
    area: "572",
    population: "85032",
    image: "https://flagcdn.com/im.svg",
  },
  {
    id: "BMU",
    name: "Bermuda",
    continents: "North America",
    capital: "Hamilton",
    subregion: "North America",
    area: "54",
    population: "63903",
    image: "https://flagcdn.com/bm.svg",
  },
  {
    id: "MHL",
    name: "Marshall Islands",
    continents: "Oceania",
    capital: "Majuro",
    subregion: "Micronesia",
    area: "181",
    population: "59194",
    image: "https://flagcdn.com/mh.svg",
  },
  {
    id: "TGO",
    name: "Togo",
    continents: "Africa",
    capital: "Lomé",
    subregion: "Western Africa",
    area: "56785",
    population: "8278737",
    image: "https://flagcdn.com/tg.svg",
  },
  {
    id: "COM",
    name: "Comoros",
    continents: "Africa",
    capital: "Moroni",
    subregion: "Eastern Africa",
    area: "1862",
    population: "869595",
    image: "https://flagcdn.com/km.svg",
  },
  {
    id: "CAN",
    name: "Canada",
    continents: "North America",
    capital: "Ottawa",
    subregion: "North America",
    area: "9984670",
    population: "38005238",
    image: "https://flagcdn.com/ca.svg",
  },
  {
    id: "NER",
    name: "Niger",
    continents: "Africa",
    capital: "Niamey",
    subregion: "Western Africa",
    area: "1267000",
    population: "24206636",
    image: "https://flagcdn.com/ne.svg",
  },
  {
    id: "HRV",
    name: "Croatia",
    continents: "Europe",
    capital: "Zagreb",
    subregion: "Southeast Europe",
    area: "56594",
    population: "4047200",
    image: "https://flagcdn.com/hr.svg",
  },
  {
    id: "ASM",
    name: "American Samoa",
    continents: "Oceania",
    capital: "Pago Pago",
    subregion: "Polynesia",
    area: "199",
    population: "55197",
    image: "https://flagcdn.com/as.svg",
  },
  {
    id: "ATF",
    name: "French Southern and Antarctic Lands",
    continents: "Antarctica",
    capital: "Port-aux-Français",
    subregion: "undefined",
    area: "7747",
    population: "400",
    image: "https://flagcdn.com/tf.svg",
  },
  {
    id: "GIN",
    name: "Guinea",
    continents: "Africa",
    capital: "Conakry",
    subregion: "Western Africa",
    area: "245857",
    population: "13132792",
    image: "https://flagcdn.com/gn.svg",
  },
  {
    id: "CUW",
    name: "Curaçao",
    continents: "North America",
    capital: "Willemstad",
    subregion: "Caribbean",
    area: "444",
    population: "155014",
    image: "https://flagcdn.com/cw.svg",
  },
  {
    id: "PRI",
    name: "Puerto Rico",
    continents: "North America",
    capital: "San Juan",
    subregion: "Caribbean",
    area: "8870",
    population: "3194034",
    image: "https://flagcdn.com/pr.svg",
  },
  {
    id: "NOR",
    name: "Norway",
    continents: "Europe",
    capital: "Oslo",
    subregion: "Northern Europe",
    area: "323802",
    population: "5379475",
    image: "https://flagcdn.com/no.svg",
  },
  {
    id: "SRB",
    name: "Serbia",
    continents: "Europe",
    capital: "Belgrade",
    subregion: "Southeast Europe",
    area: "88361",
    population: "6908224",
    image: "https://flagcdn.com/rs.svg",
  },
  {
    id: "SGS",
    name: "South Georgia",
    continents: "Antarctica",
    capital: "King Edward Point",
    subregion: "undefined",
    area: "3903",
    population: "30",
    image: "https://flagcdn.com/gs.svg",
  },
  {
    id: "GRC",
    name: "Greece",
    continents: "Europe",
    capital: "Athens",
    subregion: "Southern Europe",
    area: "131990",
    population: "10715549",
    image: "https://flagcdn.com/gr.svg",
  },
  {
    id: "TCD",
    name: "Chad",
    continents: "Africa",
    capital: "N'Djamena",
    subregion: "Middle Africa",
    area: "1284000",
    population: "16425859",
    image: "https://flagcdn.com/td.svg",
  },
  {
    id: "ARG",
    name: "Argentina",
    continents: "South America",
    capital: "Buenos Aires",
    subregion: "South America",
    area: "2780400",
    population: "45376763",
    image: "https://flagcdn.com/ar.svg",
  },
  {
    id: "BRN",
    name: "Brunei",
    continents: "Asia",
    capital: "Bandar Seri Begawan",
    subregion: "South-Eastern Asia",
    area: "5765",
    population: "437483",
    image: "https://flagcdn.com/bn.svg",
  },
  {
    id: "JPN",
    name: "Japan",
    continents: "Asia",
    capital: "Tokyo",
    subregion: "Eastern Asia",
    area: "377930",
    population: "125836021",
    image: "https://flagcdn.com/jp.svg",
  },
  {
    id: "GTM",
    name: "Guatemala",
    continents: "North America",
    capital: "Guatemala City",
    subregion: "Central America",
    area: "108889",
    population: "16858333",
    image: "https://flagcdn.com/gt.svg",
  },
  {
    id: "MMR",
    name: "Myanmar",
    continents: "Asia",
    capital: "Naypyidaw",
    subregion: "South-Eastern Asia",
    area: "676578",
    population: "54409794",
    image: "https://flagcdn.com/mm.svg",
  },
  {
    id: "BGR",
    name: "Bulgaria",
    continents: "Europe",
    capital: "Sofia",
    subregion: "Southeast Europe",
    area: "110879",
    population: "6927288",
    image: "https://flagcdn.com/bg.svg",
  },
  {
    id: "GIB",
    name: "Gibraltar",
    continents: "Europe",
    capital: "Gibraltar",
    subregion: "Southern Europe",
    area: "6",
    population: "33691",
    image: "https://flagcdn.com/gi.svg",
  },
  {
    id: "GNQ",
    name: "Equatorial Guinea",
    continents: "Africa",
    capital: "Malabo",
    subregion: "Middle Africa",
    area: "28051",
    population: "1402985",
    image: "https://flagcdn.com/gq.svg",
  },
  {
    id: "COL",
    name: "Colombia",
    continents: "South America",
    capital: "Bogotá",
    subregion: "South America",
    area: "1141748",
    population: "50882884",
    image: "https://flagcdn.com/co.svg",
  },
  {
    id: "IRN",
    name: "Iran",
    continents: "Asia",
    capital: "Tehran",
    subregion: "Southern Asia",
    area: "1648195",
    population: "83992953",
    image: "https://flagcdn.com/ir.svg",
  },
  {
    id: "NGA",
    name: "Nigeria",
    continents: "Africa",
    capital: "Abuja",
    subregion: "Western Africa",
    area: "923768",
    population: "206139587",
    image: "https://flagcdn.com/ng.svg",
  },
  {
    id: "PNG",
    name: "Papua New Guinea",
    continents: "Oceania",
    capital: "Port Moresby",
    subregion: "Melanesia",
    area: "462840",
    population: "8947027",
    image: "https://flagcdn.com/pg.svg",
  },
  {
    id: "MAF",
    name: "Saint Martin",
    continents: "North America",
    capital: "Marigot",
    subregion: "Caribbean",
    area: "53",
    population: "38659",
    image: "https://flagcdn.com/mf.svg",
  },
  {
    id: "TWN",
    name: "Taiwan",
    continents: "Asia",
    capital: "Taipei",
    subregion: "Eastern Asia",
    area: "36193",
    population: "23503349",
    image: "https://flagcdn.com/tw.svg",
  },
  {
    id: "TJK",
    name: "Tajikistan",
    continents: "Asia",
    capital: "Dushanbe",
    subregion: "Central Asia",
    area: "143100",
    population: "9537642",
    image: "https://flagcdn.com/tj.svg",
  },
  {
    id: "GUF",
    name: "French Guiana",
    continents: "South America",
    capital: "Cayenne",
    subregion: "South America",
    area: "83534",
    population: "254541",
    image: "https://flagcdn.com/gf.svg",
  },
  {
    id: "POL",
    name: "Poland",
    continents: "Europe",
    capital: "Warsaw",
    subregion: "Central Europe",
    area: "312679",
    population: "37950802",
    image: "https://flagcdn.com/pl.svg",
  },
  {
    id: "DZA",
    name: "Algeria",
    continents: "Africa",
    capital: "Algiers",
    subregion: "Northern Africa",
    area: "2381741",
    population: "44700000",
    image: "https://flagcdn.com/dz.svg",
  },
  {
    id: "KWT",
    name: "Kuwait",
    continents: "Asia",
    capital: "Kuwait City",
    subregion: "Western Asia",
    area: "17818",
    population: "4270563",
    image: "https://flagcdn.com/kw.svg",
  },
  {
    id: "DOM",
    name: "Dominican Republic",
    continents: "North America",
    capital: "Santo Domingo",
    subregion: "Caribbean",
    area: "48671",
    population: "10847904",
    image: "https://flagcdn.com/do.svg",
  },
  {
    id: "SEN",
    name: "Senegal",
    continents: "Africa",
    capital: "Dakar",
    subregion: "Western Africa",
    area: "196722",
    population: "16743930",
    image: "https://flagcdn.com/sn.svg",
  },
  {
    id: "DEU",
    name: "Germany",
    continents: "Europe",
    capital: "Berlin",
    subregion: "Western Europe",
    area: "357114",
    population: "83240525",
    image: "https://flagcdn.com/de.svg",
  },
  {
    id: "GBR",
    name: "United Kingdom",
    continents: "Europe",
    capital: "London",
    subregion: "Northern Europe",
    area: "242900",
    population: "67215293",
    image: "https://flagcdn.com/gb.svg",
  },
  {
    id: "ZWE",
    name: "Zimbabwe",
    continents: "Africa",
    capital: "Harare",
    subregion: "Southern Africa",
    area: "390757",
    population: "14862927",
    image: "https://flagcdn.com/zw.svg",
  },
  {
    id: "FJI",
    name: "Fiji",
    continents: "Oceania",
    capital: "Suva",
    subregion: "Melanesia",
    area: "18272",
    population: "896444",
    image: "https://flagcdn.com/fj.svg",
  },
  {
    id: "CYM",
    name: "Cayman Islands",
    continents: "North America",
    capital: "George Town",
    subregion: "Caribbean",
    area: "264",
    population: "65720",
    image: "https://flagcdn.com/ky.svg",
  },
  {
    id: "KOR",
    name: "South Korea",
    continents: "Asia",
    capital: "Seoul",
    subregion: "Eastern Asia",
    area: "100210",
    population: "51780579",
    image: "https://flagcdn.com/kr.svg",
  },
  {
    id: "ESP",
    name: "Spain",
    continents: "Europe",
    capital: "Madrid",
    subregion: "Southern Europe",
    area: "505992",
    population: "47351567",
    image: "https://flagcdn.com/es.svg",
  },
  {
    id: "GRL",
    name: "Greenland",
    continents: "North America",
    capital: "Nuuk",
    subregion: "North America",
    area: "2166086",
    population: "56367",
    image: "https://flagcdn.com/gl.svg",
  },
  {
    id: "VAT",
    name: "Vatican City",
    continents: "Europe",
    capital: "Vatican City",
    subregion: "Southern Europe",
    area: "0.44",
    population: "451",
    image: "https://flagcdn.com/va.svg",
  },
  {
    id: "LVA",
    name: "Latvia",
    continents: "Europe",
    capital: "Riga",
    subregion: "Northern Europe",
    area: "64559",
    population: "1901548",
    image: "https://flagcdn.com/lv.svg",
  },
  {
    id: "SXM",
    name: "Sint Maarten",
    continents: "North America",
    capital: "Philipsburg",
    subregion: "Caribbean",
    area: "34",
    population: "40812",
    image: "https://flagcdn.com/sx.svg",
  },
  {
    id: "VCT",
    name: "Saint Vincent and the Grenadines",
    continents: "North America",
    capital: "Kingstown",
    subregion: "Caribbean",
    area: "389",
    population: "110947",
    image: "https://flagcdn.com/vc.svg",
  },
  {
    id: "EGY",
    name: "Egypt",
    continents: "Africa",
    capital: "Cairo",
    subregion: "Northern Africa",
    area: "1002450",
    population: "102334403",
    image: "https://flagcdn.com/eg.svg",
  },
  {
    id: "BTN",
    name: "Bhutan",
    continents: "Asia",
    capital: "Thimphu",
    subregion: "Southern Asia",
    area: "38394",
    population: "771612",
    image: "https://flagcdn.com/bt.svg",
  },
  {
    id: "BRB",
    name: "Barbados",
    continents: "North America",
    capital: "Bridgetown",
    subregion: "Caribbean",
    area: "430",
    population: "287371",
    image: "https://flagcdn.com/bb.svg",
  },
  {
    id: "HUN",
    name: "Hungary",
    continents: "Europe",
    capital: "Budapest",
    subregion: "Central Europe",
    area: "93028",
    population: "9749763",
    image: "https://flagcdn.com/hu.svg",
  },
  {
    id: "PHL",
    name: "Philippines",
    continents: "Asia",
    capital: "Manila",
    subregion: "South-Eastern Asia",
    area: "342353",
    population: "109581085",
    image: "https://flagcdn.com/ph.svg",
  },
  {
    id: "UMI",
    name: "United States Minor Outlying Islands",
    continents: "Oceania",
    capital: "undefined",
    subregion: "North America",
    area: "34.2",
    population: "300",
    image: "https://flagcdn.com/um.svg",
  },
  {
    id: "AUT",
    name: "Austria",
    continents: "Europe",
    capital: "Vienna",
    subregion: "Central Europe",
    area: "83871",
    population: "8917205",
    image: "https://flagcdn.com/at.svg",
  },
  {
    id: "SWE",
    name: "Sweden",
    continents: "Europe",
    capital: "Stockholm",
    subregion: "Northern Europe",
    area: "450295",
    population: "10353442",
    image: "https://flagcdn.com/se.svg",
  },
  {
    id: "MUS",
    name: "Mauritius",
    continents: "Africa",
    capital: "Port Louis",
    subregion: "Eastern Africa",
    area: "2040",
    population: "1265740",
    image: "https://flagcdn.com/mu.svg",
  },
  {
    id: "SSD",
    name: "South Sudan",
    continents: "Africa",
    capital: "Juba",
    subregion: "Middle Africa",
    area: "619745",
    population: "11193729",
    image: "https://flagcdn.com/ss.svg",
  },
  {
    id: "TLS",
    name: "Timor-Leste",
    continents: "Oceania",
    capital: "Dili",
    subregion: "South-Eastern Asia",
    area: "14874",
    population: "1318442",
    image: "https://flagcdn.com/tl.svg",
  },
  {
    id: "ROU",
    name: "Romania",
    continents: "Europe",
    capital: "Bucharest",
    subregion: "Southeast Europe",
    area: "238391",
    population: "19286123",
    image: "https://flagcdn.com/ro.svg",
  },
  {
    id: "TUN",
    name: "Tunisia",
    continents: "Africa",
    capital: "Tunis",
    subregion: "Northern Africa",
    area: "163610",
    population: "11818618",
    image: "https://flagcdn.com/tn.svg",
  },
  {
    id: "IDN",
    name: "Indonesia",
    continents: "Asia",
    capital: "Jakarta",
    subregion: "South-Eastern Asia",
    area: "1904569",
    population: "273523621",
    image: "https://flagcdn.com/id.svg",
  },
  {
    id: "RUS",
    name: "Russia",
    continents: "Europe",
    capital: "Moscow",
    subregion: "Eastern Europe",
    area: "17098242",
    population: "144104080",
    image: "https://flagcdn.com/ru.svg",
  },
  {
    id: "WSM",
    name: "Samoa",
    continents: "Oceania",
    capital: "Apia",
    subregion: "Polynesia",
    area: "2842",
    population: "198410",
    image: "https://flagcdn.com/ws.svg",
  },
  {
    id: "TUV",
    name: "Tuvalu",
    continents: "Oceania",
    capital: "Funafuti",
    subregion: "Polynesia",
    area: "26",
    population: "11792",
    image: "https://flagcdn.com/tv.svg",
  },
  {
    id: "MLI",
    name: "Mali",
    continents: "Africa",
    capital: "Bamako",
    subregion: "Western Africa",
    area: "1240192",
    population: "20250834",
    image: "https://flagcdn.com/ml.svg",
  },
  {
    id: "SOM",
    name: "Somalia",
    continents: "Africa",
    capital: "Mogadishu",
    subregion: "Eastern Africa",
    area: "637657",
    population: "15893219",
    image: "https://flagcdn.com/so.svg",
  },
  {
    id: "BHR",
    name: "Bahrain",
    continents: "Asia",
    capital: "Manama",
    subregion: "Western Asia",
    area: "765",
    population: "1701583",
    image: "https://flagcdn.com/bh.svg",
  },
  {
    id: "UNK",
    name: "Kosovo",
    continents: "Europe",
    capital: "Pristina",
    subregion: "Southeast Europe",
    area: "10908",
    population: "1775378",
    image: "https://flagcdn.com/xk.svg",
  },
  {
    id: "ITA",
    name: "Italy",
    continents: "Europe",
    capital: "Rome",
    subregion: "Southern Europe",
    area: "301336",
    population: "59554023",
    image: "https://flagcdn.com/it.svg",
  },
  {
    id: "HND",
    name: "Honduras",
    continents: "North America",
    capital: "Tegucigalpa",
    subregion: "Central America",
    area: "112492",
    population: "9904608",
    image: "https://flagcdn.com/hn.svg",
  },
  {
    id: "BEN",
    name: "Benin",
    continents: "Africa",
    capital: "Porto-Novo",
    subregion: "Western Africa",
    area: "112622",
    population: "12123198",
    image: "https://flagcdn.com/bj.svg",
  },
  {
    id: "BES",
    name: "Caribbean Netherlands",
    continents: "North America",
    capital: "Kralendijk",
    subregion: "Caribbean",
    area: "328",
    population: "25987",
    image: "https://flagcdn.com/bq.svg",
  },
  {
    id: "SYR",
    name: "Syria",
    continents: "Asia",
    capital: "Damascus",
    subregion: "Western Asia",
    area: "185180",
    population: "17500657",
    image: "https://flagcdn.com/sy.svg",
  },
  {
    id: "CMR",
    name: "Cameroon",
    continents: "Africa",
    capital: "Yaoundé",
    subregion: "Middle Africa",
    area: "475442",
    population: "26545864",
    image: "https://flagcdn.com/cm.svg",
  },
  {
    id: "BGD",
    name: "Bangladesh",
    continents: "Asia",
    capital: "Dhaka",
    subregion: "Southern Asia",
    area: "147570",
    population: "164689383",
    image: "https://flagcdn.com/bd.svg",
  },
  {
    id: "SYC",
    name: "Seychelles",
    continents: "Africa",
    capital: "Victoria",
    subregion: "Eastern Africa",
    area: "452",
    population: "98462",
    image: "https://flagcdn.com/sc.svg",
  },
  {
    id: "BHS",
    name: "Bahamas",
    continents: "North America",
    capital: "Nassau",
    subregion: "Caribbean",
    area: "13943",
    population: "393248",
    image: "https://flagcdn.com/bs.svg",
  },
  {
    id: "DNK",
    name: "Denmark",
    continents: "Europe",
    capital: "Copenhagen",
    subregion: "Northern Europe",
    area: "43094",
    population: "5831404",
    image: "https://flagcdn.com/dk.svg",
  },
  {
    id: "YEM",
    name: "Yemen",
    continents: "Asia",
    capital: "Sana'a",
    subregion: "Western Asia",
    area: "527968",
    population: "29825968",
    image: "https://flagcdn.com/ye.svg",
  },
  {
    id: "TON",
    name: "Tonga",
    continents: "Oceania",
    capital: "Nuku'alofa",
    subregion: "Polynesia",
    area: "747",
    population: "105697",
    image: "https://flagcdn.com/to.svg",
  },
  {
    id: "PAK",
    name: "Pakistan",
    continents: "Asia",
    capital: "Islamabad",
    subregion: "Southern Asia",
    area: "881912",
    population: "220892331",
    image: "https://flagcdn.com/pk.svg",
  },
  {
    id: "REU",
    name: "Réunion",
    continents: "Africa",
    capital: "Saint-Denis",
    subregion: "Eastern Africa",
    area: "2511",
    population: "840974",
    image: "https://flagcdn.com/re.svg",
  },
];

const urlNamePopulation = url.map(({ name, population }) => ({
  name,
  population,
}));

urlNamePopulation.sort((a, b) => b.population - a.population);

console.log(urlNamePopulation);

module.exports = url;
